name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  unit-tests:
    timeout-minutes: 120
    runs-on: "ubuntu-20.04"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: VirtusLab/scala-cli-setup@d37cecaf2c23ee668ec7e5da04eb6da66ae9fab6
      with:
        jvm: "temurin:17"
    - name: Copy launcher
      run: ./mill -i copyJvmLauncher artifacts/
      if: runner.os == 'Linux'
    - uses: actions/upload-artifact@v3
      if: runner.os == 'Linux'
      with:
        name: launchers
        path: artifacts/
        if-no-files-found: error
        retention-days: 2
    - name: Compile everything
      run: ./mill -i __.compile
    - name: Unit tests
      run: ./mill -i unitTests

  jvm-tests-1:
    timeout-minutes: 120
    runs-on: "ubuntu-20.04"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: VirtusLab/scala-cli-setup@d37cecaf2c23ee668ec7e5da04eb6da66ae9fab6
      with:
        jvm: "temurin:17"
    - name: JVM integration tests
      run: ./mill -i integration.test.jvm
      env:
        SCALA_CLI_IT_GROUP: 1

  jvm-tests-2:
    timeout-minutes: 120
    runs-on: "ubuntu-20.04"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: VirtusLab/scala-cli-setup@d37cecaf2c23ee668ec7e5da04eb6da66ae9fab6
      with:
        jvm: "temurin:17"
    - name: JVM integration tests
      run: ./mill -i integration.test.jvm
      env:
        SCALA_CLI_IT_GROUP: 2

  jvm-tests-3:
    timeout-minutes: 120
    runs-on: "ubuntu-20.04"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: VirtusLab/scala-cli-setup@d37cecaf2c23ee668ec7e5da04eb6da66ae9fab6
      with:
        jvm: "temurin:17"
    - name: JVM integration tests
      run: ./mill -i integration.test.jvm
      env:
        SCALA_CLI_IT_GROUP: 3